INSERT INTO items (id,
                   r_id,
                   item_name,
                   item_type,
                   item_grade,
                   description,
                   price,
                   sell_price,
                   created_at,
                   updated_at)
VALUES (1,
        'sword_001',
        '연습용 검',
        'WEAPON',
        'COMMON',
        '초보자용 기본 검입니다.',
        100,
        50,
        NOW(),
        NOW()),
       (2,
        'sword_002',
        '강철 검',
        'WEAPON',
        'UNCOMMON',
        '단단한 강철로 만들어진 검입니다.',
        500,
        250,
        NOW(),
        NOW()),
       (3,
        'bow_001',
        '사냥꾼의 활',
        'WEAPON',
        'RARE',
        '먼 거리의 적을 공격할 수 있는 활입니다.',
        1200,
        600,
        NOW(),
        NOW()),
       (4,
        'armor_001',
        '가죽 갑옷',
        'ARMOR',
        'COMMON',
        '기본적인 방어력을 제공하는 가죽 갑옷입니다.',
        150,
        70,
        NOW(),
        NOW()),
       (5,
        'armor_002',
        '강철 갑옷',
        'ARMOR',
        'RARE',
        '높은 방어력을 제공하는 강철 갑옷입니다.',
        1500,
        750,
        NOW(),
        NOW()),
       (6,
        'potion_001',
        '체력 회복 물약',
        'CONSUMABLE',
        'COMMON',
        '체력을 소량 회복하는 기본 물약입니다.',
        50,
        20,
        NOW(),
        NOW()),
       (7,
        'potion_002',
        '상급 체력 회복 물약',
        'CONSUMABLE',
        'UNCOMMON',
        '체력을 중간 정도 회복하는 물약입니다.',
        200,
        80,
        NOW(),
        NOW()),
       (8,
        'elixir_001',
        '고대의 비약',
        'CONSUMABLE',
        'EPIC',
        '희귀한 재료로 만들어진 강력한 비약입니다.',
        3000,
        1500,
        NOW(),
        NOW()),
       (9,
        'ring_001',
        '행운의 반지',
        'ETC',
        'EPIC',
        '착용자에게 행운을 가져다준다고 알려진 반지입니다.',
        5000,
        2500,
        NOW(),
        NOW()),
       (10,
        'relic_001',
        '전설의 유물',
        'ETC',
        'LEGENDARY',
        '오래된 전설 속에서 전해지는 신비한 유물입니다.',
        10000,
        5000,
        NOW(),
        NOW());

INSERT INTO users (id,
                   email,
                   password,
                   nickname,
                   role,
                   status,
                   provider,
                   profile_image_url,
                   created_at,
                   updated_at)
VALUES (1,
        'user1@test.com',
        'password',
        '유저1',
        'USER',
        'ACTIVE',
        'LOCAL',
        null,
        NOW(),
        NOW()),
       (2,
        'user2@test.com',
        'password',
        '유저2',
        'USER',
        'ACTIVE',
        'LOCAL',
        null,
        NOW(),
        NOW()),
       (3,
        'user3@test.com',
        'password',
        '유저3',
        'USER',
        'ACTIVE',
        'LOCAL',
        null,
        NOW(),
        NOW()),
       (4,
        'user4@test.com',
        'password',
        '유저4',
        'USER',
        'ACTIVE',
        'LOCAL',
        null,
        NOW(),
        NOW()),
       (5,
        'user5@test.com',
        'password',
        '유저5',
        'USER',
        'ACTIVE',
        'LOCAL',
        null,
        NOW(),
        NOW());

INSERT INTO friend_requests (id,
                             from_user_id,
                             to_user_id,
                             friend_status,
                             created_at,
                             updated_at)
VALUES (1,
        1,
        2,
        'ACCEPTED',
        NOW(),
        NOW()),
       (2,
        3,
        1,
        'ACCEPTED',
        NOW(),
        NOW()),
       (3,
        4,
        1,
        'PENDING',
        NOW(),
        NOW());

INSERT INTO user_items (id,
                        user_id,
                        item_id,
                        quantity,
                        equipped,
                        acquired_at,
                        created_at,
                        updated_at)
VALUES (1,
        1,
        1,
        3,
        false,
        NOW(),
        NOW(),
        NOW()),
       (2,
        1,
        2,
        5,
        false,
        NOW(),
        NOW(),
        NOW()),
       (3,
        1,
        6,
        10,
        false,
        NOW(),
        NOW(),
        NOW());

INSERT INTO wallets (id,
                     user_id,
                     gold,
                     gem,
                     created_at,
                     updated_at)
VALUES (1,
        1,
        3000,
        10,
        NOW(),
        NOW());

INSERT INTO user_profiles (id,
                           user_id,
                           level,
                           exp,
                           total_play_seconds,
                           created_at,
                           updated_at)
VALUES (1,
        1,
        1,
        0,
        0,
        NOW(),
        NOW());

-- NPC
INSERT INTO npcs (id,
                  r_id,
                  name,
                  description,
                  location_key,
                  active,
                  created_at,
                  updated_at)
VALUES (1,
        'npc_shop_001',
        '상점 주인',
        '기본 아이템을 판매하는 NPC입니다.',
        'village_shop',
        true,
        NOW(),
        NOW());

-- NPC 상점 아이템
INSERT INTO npc_shop_items (id,
                            quantity,
                            sort_order,
                            npc_id,
                            item_id,
                            created_at,
                            updated_at)
VALUES (1,
        100,
        1,
        1,
        1,
        NOW(),
        NOW());